import { Anchor, Bird, CalendarRange, Cylinder, Dumbbell, Feather, Mail, Medal, Mountain, Music, Pencil, Route, Snowflake, Sprout, Trees, Trophy, UtensilsCrossed, Waves, type LucideIcon } from 'lucide-react';
import { type ArchivedWork } from './creative-works';
import { type Prerequisite, prerequisiteStatus, type ProgressionContext } from './prerequisites';
import { type SkillId } from './skill-catalog';

export type SeasonName = '春' | '夏' | '秋' | '冬';
export type ChallengeKind = '徒步' | '游泳' | '网球' | '力量' | '创作' | '烹饪';
export const challengeKinds: ChallengeKind[] = ['徒步', '游泳', '网球', '力量', '创作', '烹饪'];

export type ExpeditionRoute = {
  id: string;
  kind: ChallengeKind;
  title: string;
  desc: string;
  scene: string;
  icon: LucideIcon;
  weeks: number;
  gearCost: number;
  reward: number;
  failReward: number;
  companionBonus: number;
  companionSocial: number;
  companionRequired: boolean;
  minEnergy: number;
  minHealth: number;
  failEnergy: number;
  failHealth: number;
  season?: SeasonName;
  skillId: SkillId;
  skillPerWeek: number;
  energyPerWeek: number;
  stressPerWeek: number;
  healthPerWeek: number;
  socialPerWeek: number;
  fieldNoteTitle: string;
  purpose: string;
  impact: string;
  rewardLabel: string;
  prerequisites: Prerequisite[];
};

const termWear = {
  companionRequired: false as const,
  energyPerWeek: 1,
  stressPerWeek: 0,
  healthPerWeek: 1,
  failEnergy: 14,
  failHealth: 18,
};

const yearWear = {
  companionRequired: false as const,
  energyPerWeek: 2,
  stressPerWeek: -2,
  healthPerWeek: 2,
  failEnergy: 12,
  failHealth: 16,
};

function roundTo(value: number, step = 20) {
  return Math.round(value / step) * step;
}

/** 完成奖励 = 装备 + 每周津贴。短线约 240，整季 220，全年体力线 200、创作/烹饪 180，保证时长越长总额越高。 */
function challengePayouts(weeks: number, gearCost: number, weekly?: number) {
  const rate = weekly ?? (weeks >= 52 ? 200 : weeks >= 8 ? 220 : 240);
  const reward = roundTo(gearCost + weeks * rate);
  return {
    reward,
    failReward: weeks >= 52 ? gearCost : roundTo(gearCost * 0.7),
    companionBonus: roundTo(reward * 0.12),
  };
}

export const expeditionCatalog: ExpeditionRoute[] = [
  {
    id: 'ridge-valley',
    kind: '徒步',
    title: '河谷脊线',
    desc: '沿河谷补齐被暴雨冲走的路标，让迷路频发的旧步道重新安全开放。跑步过关即可独行；有同伴更稳。',
    scene: '脊线上风比镇上硬。新的路标立回岔路，后来的人不必再凭运气辨认方向。',
    icon: Mountain,
    weeks: 4,
    gearCost: 180,
    reward: 1080,
    failReward: 280,
    companionBonus: 160,
    companionSocial: 25,
    companionRequired: false,
    minEnergy: 42,
    minHealth: 55,
    failEnergy: 22,
    failHealth: 28,
    skillId: 'running',
    skillPerWeek: 0.35,
    energyPerWeek: -5,
    stressPerWeek: 3,
    healthPerWeek: -1,
    socialPerWeek: 0.6,
    fieldNoteTitle: '脊线上的一周',
    purpose: '补齐沿途安全路标',
    impact: '河谷旧步道恢复开放',
    rewardLabel: '护路回馈',
    prerequisites: [{ kind: 'skill', id: 'running', value: 20, label: '跑步达到 20' }],
  },
  {
    id: 'silver-traverse',
    kind: '徒步',
    title: '银叶横断',
    desc: '六周穿过银叶林，调查病变树木并为保护区留下完整记录。必须有同伴，完成后获得生态守护奖励。',
    scene: '林里没有捷径。同伴负责记路，你把病变树木逐一标在图上，巡护员终于有了一份完整记录。',
    icon: Trees,
    weeks: 6,
    gearCost: 280,
    reward: 1680,
    failReward: 420,
    companionBonus: 220,
    companionSocial: 35,
    companionRequired: true,
    minEnergy: 50,
    minHealth: 62,
    failEnergy: 24,
    failHealth: 30,
    skillId: 'running',
    skillPerWeek: 0.4,
    energyPerWeek: -6,
    stressPerWeek: 4,
    healthPerWeek: -2,
    socialPerWeek: 0.9,
    fieldNoteTitle: '银叶林横断记',
    purpose: '记录林木病变范围',
    impact: '保护区取得完整巡护地图',
    rewardLabel: '生态守护奖励',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'ridge-valley', label: '先走完河谷脊线' },
      { kind: 'skill', id: 'running', value: 40, label: '跑步达到 40' },
      { kind: 'social', value: 35, label: '社交度达到 35' },
    ],
  },
  {
    id: 'north-season',
    kind: '徒步',
    title: '北境季节线',
    desc: '仅冬季出发。用八周记录冰川边界与异常裂隙，为后来者保存这一年的北境。成就回馈丰厚，风险也最高。',
    scene: '短昼里把营地支起来。新的冰川边界和异常裂隙被写进档案，这个冬天不再无人作证。',
    icon: Snowflake,
    weeks: 8,
    gearCost: 420,
    reward: 2200,
    failReward: 520,
    companionBonus: 280,
    companionSocial: 40,
    companionRequired: true,
    minEnergy: 55,
    minHealth: 68,
    failEnergy: 26,
    failHealth: 32,
    season: '冬',
    skillId: 'running',
    skillPerWeek: 0.45,
    energyPerWeek: -6,
    stressPerWeek: 5,
    healthPerWeek: -2,
    socialPerWeek: 1.1,
    fieldNoteTitle: '北境短昼',
    purpose: '记录冰川与裂隙变化',
    impact: '完成本年度北境环境档案',
    rewardLabel: '北境成就嘉奖',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'silver-traverse', label: '先走完银叶横断' },
      { kind: 'skill', id: 'running', value: 55, label: '跑步达到 55' },
      { kind: 'social', value: 40, label: '社交度达到 40' },
      { kind: 'week', value: 20, label: '驻留满 20 周' },
    ],
  },
  {
    id: 'reed-wetland',
    kind: '徒步',
    title: '芦湾湿地',
    desc: '沿浅水栈道清除废弃鱼线，并修复候鸟繁殖区的围护标记。适合作为第一次守护远征。',
    scene: '最后一团鱼线从芦苇根部解开。围护标记重新立好，受惊的水鸟慢慢回到浅滩。',
    icon: Bird,
    weeks: 2,
    gearCost: 90,
    reward: 420,
    failReward: 80,
    companionBonus: 60,
    companionSocial: 18,
    companionRequired: false,
    minEnergy: 34,
    minHealth: 45,
    failEnergy: 18,
    failHealth: 24,
    skillId: 'running',
    skillPerWeek: 0.2,
    energyPerWeek: -3,
    stressPerWeek: 1,
    healthPerWeek: 0,
    socialPerWeek: 0.5,
    fieldNoteTitle: '芦湾归鸟记录',
    purpose: '清理湿地并保护候鸟',
    impact: '候鸟繁殖区恢复安静',
    rewardLabel: '湿地守护谢礼',
    prerequisites: [],
  },
  {
    id: 'forgotten-mail',
    kind: '徒步',
    title: '旧线遗信',
    desc: '沿废弃铁路寻找散落多年的邮袋，把仍能辨认收件人的信送回沿线居民手中。',
    scene: '铁轨早已生锈，信上的名字却仍有人记得。最后一封信在黄昏前找到了家。',
    icon: Mail,
    weeks: 3,
    gearCost: 120,
    reward: 650,
    failReward: 120,
    companionBonus: 90,
    companionSocial: 22,
    companionRequired: false,
    minEnergy: 38,
    minHealth: 48,
    failEnergy: 20,
    failHealth: 25,
    skillId: 'running',
    skillPerWeek: 0.25,
    energyPerWeek: -4,
    stressPerWeek: 2,
    healthPerWeek: -1,
    socialPerWeek: 0.8,
    fieldNoteTitle: '寄回旧线的信',
    purpose: '寻找并送还旧信',
    impact: '沿线居民取回失落的记忆',
    rewardLabel: '居民共同赠礼',
    prerequisites: [{ kind: 'expeditionRoute', id: 'reed-wetland', label: '先完成芦湾湿地' }],
  },
  {
    id: 'heather-slope',
    kind: '徒步',
    title: '石楠坡复绿线',
    desc: '把本地草籽带上受损山坡，封闭侵蚀捷径，并完成一段不留垃圾的长距离穿越。',
    scene: '侵蚀最深的捷径被封住，草籽埋进薄土。眼下仍是荒坡，但来年会有新的颜色。',
    icon: Sprout,
    weeks: 5,
    gearCost: 230,
    reward: 1240,
    failReward: 300,
    companionBonus: 180,
    companionSocial: 30,
    companionRequired: true,
    minEnergy: 46,
    minHealth: 58,
    failEnergy: 23,
    failHealth: 29,
    skillId: 'running',
    skillPerWeek: 0.38,
    energyPerWeek: -5,
    stressPerWeek: 3,
    healthPerWeek: -1,
    socialPerWeek: 0.8,
    fieldNoteTitle: '石楠坡复绿记',
    purpose: '修复受侵蚀的山坡',
    impact: '山坡进入长期复绿',
    rewardLabel: '社区复绿回馈',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'ridge-valley', label: '先走完河谷脊线' },
      { kind: 'skill', id: 'running', value: 32, label: '跑步达到 32' },
      { kind: 'social', value: 30, label: '社交度达到 30' },
    ],
  },
  {
    id: 'mirror-lake-crossing',
    kind: '游泳',
    title: '镜湖横渡',
    desc: '在夏季完成公开水域横渡。沿线设有救援艇，完成全程会写入镜湖年度纪录。',
    scene: '清晨的湖面比想象中宽。你在最后一只浮标旁转身，完整游过了镜湖。',
    icon: Waves,
    weeks: 2,
    gearCost: 140,
    reward: 720,
    failReward: 100,
    companionBonus: 80,
    companionSocial: 24,
    companionRequired: false,
    minEnergy: 42,
    minHealth: 55,
    failEnergy: 20,
    failHealth: 28,
    season: '夏',
    skillId: 'swimming',
    skillPerWeek: 0.38,
    energyPerWeek: -5,
    stressPerWeek: 3,
    healthPerWeek: -1,
    socialPerWeek: 0.6,
    fieldNoteTitle: '横渡镜湖',
    purpose: '完成公开水域横渡',
    impact: '名字写入镜湖年度纪录',
    rewardLabel: '横渡成就奖励',
    prerequisites: [
      { kind: 'course', id: 'swim', label: '完成游泳课' },
      { kind: 'skill', id: 'swimming', value: 25, label: '游泳达到 25' },
    ],
  },
  {
    id: 'rose-city-open',
    kind: '网球',
    title: '玫瑰城公开赛',
    desc: '参加面向各地业余选手的公开赛。完成全部赛程即可取得年度参赛章，成绩优秀还有额外回馈。',
    scene: '最后一球落在界内。无论名次如何，你完成了第一次正式的异地赛程。',
    icon: Trophy,
    weeks: 2,
    gearCost: 180,
    reward: 880,
    failReward: 120,
    companionBonus: 100,
    companionSocial: 28,
    companionRequired: false,
    minEnergy: 45,
    minHealth: 54,
    failEnergy: 20,
    failHealth: 26,
    skillId: 'tennis',
    skillPerWeek: 0.4,
    energyPerWeek: -5,
    stressPerWeek: 4,
    healthPerWeek: -1,
    socialPerWeek: 0.9,
    fieldNoteTitle: '玫瑰城赛场札记',
    purpose: '完成异地公开赛',
    impact: '取得本年度公开赛参赛章',
    rewardLabel: '赛事成就奖励',
    prerequisites: [
      { kind: 'course', id: 'tennis', label: '完成网球课' },
      { kind: 'skill', id: 'tennis', value: 25, label: '网球达到 25' },
    ],
  },
  {
    id: 'granite-seven',
    kind: '力量',
    title: '花岗岩七关',
    desc: '在山城完成搬石、负重与攀绳组成的七项挑战。它检验长期训练成果，不要求竞速。',
    scene: '第七关的石块终于越过刻线。看台没有喧闹太久，训练留下的力量却真实可见。',
    icon: Dumbbell,
    weeks: 3,
    gearCost: 210,
    reward: 1080,
    failReward: 180,
    companionBonus: 120,
    companionSocial: 30,
    companionRequired: false,
    minEnergy: 48,
    minHealth: 60,
    failEnergy: 22,
    failHealth: 29,
    skillId: 'strength',
    skillPerWeek: 0.43,
    energyPerWeek: -6,
    stressPerWeek: 4,
    healthPerWeek: -1,
    socialPerWeek: 0.6,
    fieldNoteTitle: '花岗岩七关',
    purpose: '完成七项力量关卡',
    impact: '达成长距离负重里程碑',
    rewardLabel: '力量里程碑奖励',
    prerequisites: [
      { kind: 'skill', id: 'strength', value: 30, label: '力量训练达到 30' },
      { kind: 'week', value: 12, label: '驻留满 12 周' },
    ],
  },
  {
    id: 'lighthouse-writing',
    kind: '创作',
    title: '灯塔七日写作',
    desc: '在旧灯塔完成限时写作挑战，并把最终作品交给沿海公共阅览室收藏。',
    scene: '第七夜潮声未停，最后一页已经写完。作品被放进阅览室，等待陌生读者翻开。',
    icon: Feather,
    weeks: 1,
    gearCost: 80,
    reward: 460,
    failReward: 60,
    companionBonus: 40,
    companionSocial: 20,
    companionRequired: false,
    minEnergy: 32,
    minHealth: 38,
    failEnergy: 15,
    failHealth: 20,
    skillId: 'writing',
    skillPerWeek: 0.5,
    energyPerWeek: -3,
    stressPerWeek: 4,
    healthPerWeek: 0,
    socialPerWeek: 0.4,
    fieldNoteTitle: '灯塔第七夜',
    purpose: '七日内完成一篇作品',
    impact: '作品纳入沿海公共阅览室馆藏',
    rewardLabel: '作品入选奖励',
    prerequisites: [{ kind: 'skill', id: 'writing', value: 20, label: '写作达到 20' }],
  },
  {
    id: 'harbor-kitchen',
    kind: '烹饪',
    title: '海港灶台',
    desc: '在海鸥港跟早市厨子连做三天时令海鲜。完成即可把菜单交给港边公共食堂轮值。',
    scene: '第三天的汤先开了。菜单被钉在食堂门口，早市的人按你的顺序来买。',
    icon: UtensilsCrossed,
    weeks: 1,
    gearCost: 90,
    reward: 420,
    failReward: 70,
    companionBonus: 50,
    companionSocial: 18,
    companionRequired: false,
    minEnergy: 30,
    minHealth: 36,
    failEnergy: 16,
    failHealth: 22,
    skillId: 'cooking',
    skillPerWeek: 0.5,
    energyPerWeek: -3,
    stressPerWeek: 2,
    healthPerWeek: 0,
    socialPerWeek: 0.6,
    fieldNoteTitle: '海港三日菜单',
    purpose: '完成时令海鲜轮值',
    impact: '菜单进入港边公共食堂',
    rewardLabel: '食堂回馈',
    prerequisites: [{ kind: 'skill', id: 'cooking', value: 18, label: '烹饪达到 18' }],
  },
  {
    id: 'station-recital',
    kind: '创作',
    title: '月台独奏',
    desc: '在榛木镇车站大厅完成一场限时独奏。旅客来去，琴声只占午后的一段。',
    scene: '最后一首在进站广播里结束。有人停住听完，有人已经上车。',
    icon: Music,
    weeks: 1,
    gearCost: 70,
    reward: 400,
    failReward: 60,
    companionBonus: 40,
    companionSocial: 22,
    companionRequired: false,
    minEnergy: 28,
    minHealth: 34,
    failEnergy: 14,
    failHealth: 20,
    skillId: 'piano',
    skillPerWeek: 0.5,
    energyPerWeek: -3,
    stressPerWeek: 4,
    healthPerWeek: 0,
    socialPerWeek: 0.7,
    fieldNoteTitle: '月台节目单',
    purpose: '完成车站大厅独奏',
    impact: '车站为本季留下一场公开演奏',
    rewardLabel: '演出谢礼',
    prerequisites: [
      { kind: 'course', id: 'piano', label: '完成钢琴基础' },
      { kind: 'skill', id: 'piano', value: 20, label: '钢琴达到 20' },
    ],
  },
  {
    id: 'coast-sketch',
    kind: '创作',
    title: '海岸速写',
    desc: '沿海鸥港到灯塔画完一组固定机位速写，完成后交给港务阅览室陈列。',
    scene: '潮位一天变三次，画夹上全是盐。最后一张灯塔是在风停的间隙完成的。',
    icon: Pencil,
    weeks: 2,
    gearCost: 110,
    reward: 640,
    failReward: 90,
    companionBonus: 70,
    companionSocial: 22,
    companionRequired: false,
    minEnergy: 32,
    minHealth: 40,
    failEnergy: 16,
    failHealth: 22,
    skillId: 'drawing',
    skillPerWeek: 0.4,
    energyPerWeek: -3,
    stressPerWeek: 3,
    healthPerWeek: 0,
    socialPerWeek: 0.5,
    fieldNoteTitle: '灯塔速写组',
    purpose: '完成固定机位速写',
    impact: '作品陈列于港务阅览室',
    rewardLabel: '陈列回馈',
    prerequisites: [
      { kind: 'course', id: 'visual', label: '完成素描课' },
      { kind: 'skill', id: 'drawing', value: 20, label: '绘画达到 20' },
    ],
  },
  {
    id: 'river-kiln',
    kind: '创作',
    title: '河岸试烧',
    desc: '在沿河窑场独立完成一窑日用器。开窑后选出可留用的，其余回泥。',
    scene: '火候比预计多走半夜。开窑时有三件完整，其余回到泥里等下一次。',
    icon: Cylinder,
    weeks: 2,
    gearCost: 130,
    reward: 700,
    failReward: 100,
    companionBonus: 80,
    companionSocial: 24,
    companionRequired: false,
    minEnergy: 34,
    minHealth: 42,
    failEnergy: 17,
    failHealth: 24,
    skillId: 'pottery',
    skillPerWeek: 0.4,
    energyPerWeek: -4,
    stressPerWeek: 3,
    healthPerWeek: -1,
    socialPerWeek: 0.5,
    fieldNoteTitle: '河岸开窑记',
    purpose: '独立完成一窑日用器',
    impact: '可用器皿进入窑场公共架',
    rewardLabel: '窑场分成',
    prerequisites: [
      { kind: 'course', id: 'pottery', label: '完成陶艺课' },
      { kind: 'skill', id: 'pottery', value: 20, label: '陶艺达到 20' },
    ],
  },
  {
    id: 'strait-relay',
    kind: '游泳',
    title: '海峡公开水域',
    desc: '夏季限定。在镜湖横渡之后参加海峡公开水域，分段有补给船，全程计入年度纪录。',
    scene: '第二段风比湖上硬。补给船在浮标外等你，你把海峡完整游过。',
    icon: Anchor,
    weeks: 3,
    gearCost: 220,
    reward: 1180,
    failReward: 180,
    companionBonus: 140,
    companionSocial: 30,
    companionRequired: false,
    minEnergy: 50,
    minHealth: 62,
    failEnergy: 24,
    failHealth: 30,
    season: '夏',
    skillId: 'swimming',
    skillPerWeek: 0.43,
    energyPerWeek: -6,
    stressPerWeek: 4,
    healthPerWeek: -1,
    socialPerWeek: 0.7,
    fieldNoteTitle: '海峡分段',
    purpose: '完成海峡公开水域',
    impact: '名字写入海峡年度纪录',
    rewardLabel: '公开水域奖励',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'mirror-lake-crossing', label: '先完成镜湖横渡' },
      { kind: 'skill', id: 'swimming', value: 40, label: '游泳达到 40' },
    ],
  },
  {
    id: 'gull-invitational',
    kind: '网球',
    title: '海鸥港邀请赛',
    desc: '玫瑰城公开赛之后的海岸邀请赛。场地靠海，风是赛程的一部分。',
    scene: '决胜盘的球被风托了一下。你把全部场次打完，盐粒留在拍柄上。',
    icon: Medal,
    weeks: 2,
    gearCost: 240,
    reward: 1240,
    failReward: 160,
    companionBonus: 120,
    companionSocial: 32,
    companionRequired: false,
    minEnergy: 48,
    minHealth: 58,
    failEnergy: 22,
    failHealth: 28,
    skillId: 'tennis',
    skillPerWeek: 0.43,
    energyPerWeek: -5,
    stressPerWeek: 4,
    healthPerWeek: -1,
    socialPerWeek: 1,
    fieldNoteTitle: '海风赛程',
    purpose: '完成海岸邀请赛全部场次',
    impact: '取得本年度邀请赛参赛章',
    rewardLabel: '邀请赛奖励',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'rose-city-open', label: '先完成玫瑰城公开赛' },
      { kind: 'skill', id: 'tennis', value: 40, label: '网球达到 40' },
    ],
  },
  {
    id: 'ridge-season',
    kind: '徒步',
    title: '脊线护路季',
    desc: '用一季沿河谷脊线做定期巡护与路标补齐。节奏比单次穿越慢，适合把跑步练成习惯。',
    scene: '同一段风走了三个月。新路标不再是事件，而是每周要核对的清单。',
    icon: Route,
    weeks: 13,
    gearCost: 420,
    ...challengePayouts(13, 420),
    companionSocial: 28,
    ...termWear,
    minEnergy: 44,
    minHealth: 52,
    skillId: 'running',
    skillPerWeek: 0.28,
    socialPerWeek: 0.5,
    fieldNoteTitle: '护路一季',
    purpose: '完成整季脊线巡护',
    impact: '河谷步道维持可通行',
    rewardLabel: '季护回馈',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'ridge-valley', label: '先走完河谷脊线' },
      { kind: 'skill', id: 'running', value: 32, label: '跑步达到 32' },
    ],
  },
  {
    id: 'silver-year',
    kind: '徒步',
    title: '银叶巡护年',
    desc: '按年签约的银叶林巡护。病变记录、访客引导和冬季封道都算进这一年。',
    scene: '林相按季改一遍。你的笔记从横断变成一本按月翻的巡护档。',
    icon: Trees,
    weeks: 52,
    gearCost: 1280,
    ...challengePayouts(52, 1280),
    companionSocial: 35,
    ...yearWear,
    minEnergy: 48,
    minHealth: 56,
    skillId: 'running',
    skillPerWeek: 0.23,
    socialPerWeek: 0.6,
    fieldNoteTitle: '银叶巡护年记',
    purpose: '完成全年林木巡护',
    impact: '保护区保有完整年度档案',
    rewardLabel: '年护契约金',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'ridge-season', label: '先完成脊线护路季' },
      { kind: 'skill', id: 'running', value: 48, label: '跑步达到 48' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
  {
    id: 'lake-season',
    kind: '游泳',
    title: '镜湖泳季',
    desc: '夏季开始的公开水域训练季。每周固定横渡与分段，计入镜湖泳者名册。',
    scene: '浮标的位置你闭眼也知道。三个月后，湖宽不再吓人。',
    icon: Waves,
    weeks: 13,
    gearCost: 380,
    ...challengePayouts(13, 380),
    companionSocial: 26,
    ...termWear,
    minEnergy: 46,
    minHealth: 54,
    season: '夏',
    skillId: 'swimming',
    skillPerWeek: 0.28,
    socialPerWeek: 0.5,
    fieldNoteTitle: '镜湖泳季',
    purpose: '完成整季公开水域训练',
    impact: '名字写入镜湖泳者名册',
    rewardLabel: '泳季津贴',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'mirror-lake-crossing', label: '先完成镜湖横渡' },
      { kind: 'skill', id: 'swimming', value: 32, label: '游泳达到 32' },
    ],
  },
  {
    id: 'coast-year',
    kind: '游泳',
    title: '公开水域年',
    desc: '沿海公开水域的全年训练与季节赛事。不限开赛季节，按年把分段游完。',
    scene: '海水的温度按月变化。你把海峡、港湾和冬泳都写进同一本记录。',
    icon: Anchor,
    weeks: 52,
    gearCost: 1180,
    ...challengePayouts(52, 1180),
    companionSocial: 32,
    ...yearWear,
    minEnergy: 50,
    minHealth: 58,
    skillId: 'swimming',
    skillPerWeek: 0.23,
    socialPerWeek: 0.6,
    fieldNoteTitle: '公开水域年记',
    purpose: '完成全年公开水域分段',
    impact: '取得年度公开水域资格',
    rewardLabel: '年度泳者津贴',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'lake-season', label: '先完成镜湖泳季' },
      { kind: 'skill', id: 'swimming', value: 45, label: '游泳达到 45' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
  {
    id: 'circuit-season',
    kind: '网球',
    title: '城市赛季',
    desc: '玫瑰城到海鸥港的业余巡回，一季打完固定站次。风、室内馆和红土都要适应。',
    scene: '球拍的握把换过一次皮。赛程表比地图更熟。',
    icon: Trophy,
    weeks: 13,
    gearCost: 460,
    ...challengePayouts(13, 460),
    companionSocial: 30,
    ...termWear,
    minEnergy: 46,
    minHealth: 54,
    skillId: 'tennis',
    skillPerWeek: 0.28,
    socialPerWeek: 0.8,
    fieldNoteTitle: '城市赛季札记',
    purpose: '完成一季业余巡回',
    impact: '取得本季巡回积分',
    rewardLabel: '赛季积分奖励',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'rose-city-open', label: '先完成玫瑰城公开赛' },
      { kind: 'skill', id: 'tennis', value: 32, label: '网球达到 32' },
    ],
  },
  {
    id: 'tour-year',
    kind: '网球',
    title: '海岸巡回年',
    desc: '按年参加海岸沿线业余巡回。春室内、夏海风、秋红土，把一年打满。',
    scene: '同一座海港球场去过四次。观众里开始有认得你的人。',
    icon: Medal,
    weeks: 52,
    gearCost: 1360,
    ...challengePayouts(52, 1360),
    companionSocial: 36,
    ...yearWear,
    minEnergy: 50,
    minHealth: 58,
    skillId: 'tennis',
    skillPerWeek: 0.23,
    socialPerWeek: 0.8,
    fieldNoteTitle: '巡回年',
    purpose: '完成全年海岸巡回',
    impact: '取得年度巡回资格章',
    rewardLabel: '巡回年奖励',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'circuit-season', label: '先完成城市赛季' },
      { kind: 'skill', id: 'tennis', value: 45, label: '网球达到 45' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
  {
    id: 'granite-season',
    kind: '力量',
    title: '山城负重季',
    desc: '在花岗岩七关的训练场住满一季，把搬石、负重和攀绳练成每周功课。',
    scene: '第七关的刻线看了三个月。重量不再新鲜，稳定才算数。',
    icon: Dumbbell,
    weeks: 13,
    gearCost: 440,
    ...challengePayouts(13, 440),
    companionSocial: 28,
    ...termWear,
    minEnergy: 48,
    minHealth: 58,
    skillId: 'strength',
    skillPerWeek: 0.28,
    socialPerWeek: 0.4,
    fieldNoteTitle: '负重一季',
    purpose: '完成整季力量驻训',
    impact: '达成长驻负重记录',
    rewardLabel: '驻训津贴',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'granite-seven', label: '先完成花岗岩七关' },
      { kind: 'skill', id: 'strength', value: 35, label: '力量训练达到 35' },
    ],
  },
  {
    id: 'dock-year',
    kind: '力量',
    title: '码头负重年',
    desc: '在海鸥港码头按年做装卸与负重协作。它把力量训练变成一份按季节变化的活。',
    scene: '潮汐比哨声准。一年结束时，肩背比奖牌更说明问题。',
    icon: Anchor,
    weeks: 52,
    gearCost: 1120,
    ...challengePayouts(52, 1120),
    companionSocial: 30,
    ...yearWear,
    minEnergy: 50,
    minHealth: 60,
    skillId: 'strength',
    skillPerWeek: 0.23,
    socialPerWeek: 0.5,
    fieldNoteTitle: '码头年',
    purpose: '完成全年码头负重',
    impact: '取得码头年度协作资格',
    rewardLabel: '年契工酬',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'granite-season', label: '先完成山城负重季' },
      { kind: 'skill', id: 'strength', value: 45, label: '力量训练达到 45' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
  {
    id: 'light-season',
    kind: '创作',
    title: '灯塔驻笔季',
    desc: '在旧灯塔住满一季，按周交出稿件。最终汇编由沿海公共阅览室收藏。',
    scene: '潮声变成背景。三个月的稿纸叠起来，比七日写作厚出一截。',
    icon: Feather,
    weeks: 13,
    gearCost: 260,
    ...challengePayouts(13, 260, 200),
    companionSocial: 22,
    ...termWear,
    minEnergy: 34,
    minHealth: 40,
    skillId: 'writing',
    skillPerWeek: 0.3,
    socialPerWeek: 0.3,
    fieldNoteTitle: '灯塔一季',
    purpose: '完成整季驻留写作',
    impact: '季稿纳入公共阅览室',
    rewardLabel: '驻笔稿酬',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'lighthouse-writing', label: '先完成灯塔七日写作' },
      { kind: 'skill', id: 'writing', value: 28, label: '写作达到 28' },
    ],
  },
  {
    id: 'archive-year',
    kind: '创作',
    title: '阅览驻站年',
    desc: '在沿海公共阅览室驻站一年，写作、编目与公开朗读按月轮换。',
    scene: '同一张桌子对着同一扇海窗。读者换了几茬，你的年稿还在最下层。',
    icon: CalendarRange,
    weeks: 52,
    gearCost: 860,
    ...challengePayouts(52, 860, 180),
    companionSocial: 28,
    ...yearWear,
    minEnergy: 36,
    minHealth: 42,
    skillId: 'writing',
    skillPerWeek: 0.25,
    socialPerWeek: 0.5,
    fieldNoteTitle: '驻站年稿',
    purpose: '完成全年驻站写作',
    impact: '年稿进入阅览室固定架',
    rewardLabel: '驻站年薪',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'light-season', label: '先完成灯塔驻笔季' },
      { kind: 'skill', id: 'writing', value: 40, label: '写作达到 40' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
  {
    id: 'harbor-season',
    kind: '烹饪',
    title: '港湾厨季',
    desc: '在海鸥港公共食堂按季轮值，早市进货、午市出餐、把菜单按潮汛改。',
    scene: '汤的底味按月微调。三个月后，渔人开始按你的出餐时间来。',
    icon: UtensilsCrossed,
    weeks: 13,
    gearCost: 280,
    ...challengePayouts(13, 280, 200),
    companionSocial: 22,
    ...termWear,
    minEnergy: 36,
    minHealth: 42,
    skillId: 'cooking',
    skillPerWeek: 0.3,
    socialPerWeek: 0.6,
    fieldNoteTitle: '港湾季菜单',
    purpose: '完成整季食堂轮值',
    impact: '季菜单进入港湾食堂档',
    rewardLabel: '轮值津贴',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'harbor-kitchen', label: '先完成海港灶台' },
      { kind: 'skill', id: 'cooking', value: 28, label: '烹饪达到 28' },
    ],
  },
  {
    id: 'mess-year',
    kind: '烹饪',
    title: '车站食堂年',
    desc: '承包榛木镇车站食堂一年。旅客来去，菜单要按季节、学期和节庆改。',
    scene: '月台的广播比灶上的计时器响。一年结束时，常客已经有固定的座位。',
    icon: UtensilsCrossed,
    weeks: 52,
    gearCost: 920,
    ...challengePayouts(52, 920, 180),
    companionSocial: 26,
    ...yearWear,
    minEnergy: 38,
    minHealth: 44,
    skillId: 'cooking',
    skillPerWeek: 0.25,
    socialPerWeek: 0.7,
    fieldNoteTitle: '车站年菜单',
    purpose: '完成全年车站食堂',
    impact: '车站保有一套四季菜单',
    rewardLabel: '年契厨酬',
    prerequisites: [
      { kind: 'expeditionRoute', id: 'harbor-season', label: '先完成港湾厨季' },
      { kind: 'skill', id: 'cooking', value: 40, label: '烹饪达到 40' },
      { kind: 'week', value: 26, label: '驻留满 26 周' },
    ],
  },
];

export function getExpedition(id: string) {
  return expeditionCatalog.find(item => item.id === id) ?? expeditionCatalog[0];
}

export function hydrateCompletedExpeditions(raw: unknown) {
  if (!Array.isArray(raw)) return [];
  const known = new Set(expeditionCatalog.map(item => item.id));
  return [...new Set(raw.filter((id): id is string => typeof id === 'string' && known.has(id)))];
}

export function expeditionHasCompanion(route: ExpeditionRoute, sociability: number) {
  return sociability >= route.companionSocial;
}

export function expeditionWeekWear(route: ExpeditionRoute, skill: number, withCompanion: boolean) {
  const seasonedAt: Record<string, number> = {
    'reed-wetland': 25,
    'forgotten-mail': 32,
    'ridge-valley': 40,
    'heather-slope': 48,
    'silver-traverse': 55,
    'north-season': 70,
    'mirror-lake-crossing': 45,
    'rose-city-open': 45,
    'granite-seven': 50,
    'lighthouse-writing': 40,
    'harbor-kitchen': 35,
    'station-recital': 40,
    'coast-sketch': 40,
    'river-kiln': 40,
    'strait-relay': 55,
    'gull-invitational': 55,
    'ridge-season': 32,
    'silver-year': 48,
    'lake-season': 32,
    'coast-year': 45,
    'circuit-season': 32,
    'tour-year': 45,
    'granite-season': 35,
    'dock-year': 45,
    'light-season': 28,
    'archive-year': 40,
    'harbor-season': 28,
    'mess-year': 40,
  };
  const seasoned = skill / 2 >= (seasonedAt[route.id] ?? 50);
  return {
    energy: route.energyPerWeek - (seasoned ? 0 : 2),
    stress: route.stressPerWeek + (seasoned ? 0 : 2) - (withCompanion ? 1 : 0),
    health: route.healthPerWeek - (seasoned ? 0 : 2),
    social: withCompanion ? route.socialPerWeek : 0,
    skillId: route.skillId,
    skill: route.skillPerWeek,
  };
}

export function expeditionFailed(route: ExpeditionRoute, energy: number, health: number) {
  return energy < route.failEnergy || health < route.failHealth;
}

export function expeditionPayout(route: ExpeditionRoute, success: boolean, withCompanion: boolean) {
  if (!success) return route.failReward;
  return route.reward + (withCompanion ? route.companionBonus : 0);
}

export function expeditionStartIssues(route: ExpeditionRoute, input: {
  funds: number;
  remainingWeeks: number;
  energy: number;
  health: number;
  sociability: number;
  season: SeasonName;
  context: ProgressionContext;
}) {
  const issues = [...prerequisiteStatus(route.prerequisites, input.context).missing];
  if (input.funds < route.gearCost) issues.push('余额不够装备');
  if (route.weeks > input.remainingWeeks) issues.push('驻留期不够');
  if (input.energy < route.minEnergy) issues.push(`精力需 ${route.minEnergy}`);
  if (input.health < route.minHealth) issues.push(`体能需 ${route.minHealth}`);
  if (route.season && input.season !== route.season) issues.push(`仅${route.season}季可出发`);
  return issues;
}

export function expeditionFieldNote(route: ExpeditionRoute, week: number, writingSkill: number): ArchivedWork | null {
  if (route.id === 'silver-traverse' && writingSkill < 20) return null;
  return {
    id: `expedition-${route.id}-${week}`,
    skillId: 'writing',
    formId: 'write-journal',
    title: route.fieldNoteTitle,
    formTitle: route.kind === '创作' || route.kind === '烹饪' ? '挑战作品' : '挑战记录',
    lengthLabel: '行记',
    slots: Math.min(route.weeks, 6),
    week,
  };
}
